version: '3.7'

services:
  webapigateway:
    image: ${DOCKER_REGISTRY-}webapigateway
    build:
      context: .
      dockerfile: src/Services/WebApiGateway/Dockerfile

  event.api:
    image: ${DOCKER_REGISTRY-}eventapi
    build:
      context: .
      dockerfile: src/Services/Event/Event.Api/Dockerfile


  event.grpc:
    image: ${DOCKER_REGISTRY-}eventgrpc
    build:
      context: .
      dockerfile: src/Services/Event/Event.Grpc/Dockerfile


  slip.api:
    image: ${DOCKER_REGISTRY-}slipapi
    build:
      context: .
      dockerfile: src/Services/Slip/Slip.Api/Dockerfile

networks:
  odin:
    name: odin-network